name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Publish tweet
        uses: StanleyMasinde/twitter-action@v1
        with:
          body: "Testing Twitter CLI from GH Actions."
          twitter_version: latest
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
          bearer_token: ${{ secrets.TWITTER_BEARER_TOKEN }}
